name: FGA
version: "1.5.0"
license: "GPL-2.0-or-later"
date: 2023-04-04
description: |
    Free Group Algorithms

authors:
    - name: Christian Sievers
      url: mailto:c.sievers@tu-bs.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/fga/
readme: README.md
packageinfo: https://gap-packages.github.io/fga/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fga/releases/download/v1.5.0/fga-1.5.0.tar.gz

abstract: |
    The <span class="pkgname">FGA</span> package installs methods for    computations with finitely generated subgroups of free groups and    provides a presentation for their automorphism groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    free groups, inverse finite automata, basic coset enumeration, finite presentation of the automorphism group of a free group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ST23</span>]   <b class='BibAuthor'>Sievers, C. and GAP Team, T.</b>,
     <i class='BibTitle'>FGA, Free Group Algorithms,
             Version 1.5.0</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/fga/">https://gap-packages.github.io/fga/</a></span>.
    </p>
    

bibtex: |
    @misc{ FGA1.5.0,
      author =           {Sievers, C. and GAP Team, T.},
      title =            {{FGA}, Free Group Algorithms, {V}ersion 1.5.0},
      month =            {Apr},
      year =             {2023},
      note =             {Refereed GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/fga/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{fga/}}},
      keywords =         {free  groups;  inverse  finite  automata;  basic coset
                          enumeration;  finite  presentation of the automorphism
                          group of a free group},
      printedkey =       {ST23}
    }

