name: FGA
version: "1.5.0-DEV"
license: "GPL-2.0-or-later"
date: 2018-03-23
description: |
    Free Group Algorithms

authors:
    - name: Christian Sievers
      url: mailto:c.sievers@tu-bs.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/fga/
readme: README.md
packageinfo: https://gap-packages.github.io/fga/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://gap-packages.github.io/fga/FGA-1.5.0-DEV.tar.gz

abstract: |
    The <span class="pkgname">FGA</span> package installs methods for    computations with finitely generated subgroups of free groups and    provides a presentation for their automorphism groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    free groups, inverse finite automata, basic coset enumeration, finite presentation of the automorphism group of a free group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ST18</span>]   <b class='BibAuthor'>Sievers, C. and GAP Team, T.</b>,
     <i class='BibTitle'>FGA, Free Group Algorithms,
             Version 1.5.0-DEV</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/fga/">https://gap-packages.github.io/fga/</a></span>.
    </p>
    

bibtex: |
    @misc{ FGA1.5.0-DEV,
      author =           {Sievers, C. and GAP Team, T.},
      title =            {{FGA}, Free Group Algorithms, {V}ersion 1.5.0-DEV},
      month =            {Mar},
      year =             {2018},
      note =             {Refereed GAP package},
      howpublished =     {\href                                                {https://gap-packages.github.io/fga/}
                          {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{fga/}}},
      keywords =         {free  groups; inverse finite automata; basic coset enumeration; finite presentation of the
                          automorphism group of a free group},
      printedkey =       {ST18}
    }

